const Svg = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="svg w-100">
    {/* Horizontal grid lines for reference */}
    {/* ... (horizontal grid lines) */}
    <line
      x1="5%"
      y1="5%"
      x2="5%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    <line
      x1="19%"
      y1="5%"
      x2="19%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    <line
      x1="33%"
      y1="5%"
      x2="33%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    <line
      x1="46%"
      y1="5%"
      x2="46%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    <line
      x1="60%"
      y1="5%"
      x2="60%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    <line
      x1="74%"
      y1="5%"
      x2="74%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    <line
      x1="88%"
      y1="5%"
      x2="88%"
      y2="95%"
      stroke="#000"
      strokeDasharray="5"
      strokeWidth="0.5"
    />
    {/* Rectangles representing data */}
    {/* You may adjust the dimensions and colors as needed */}
    {/* ... (rectangles for userSignUp and userSubscribed) */}
    <rect
      x="49%"
      y="22.5%"
      width="1%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="48%"
      y="25%"
      width="2%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="47%"
      y="27.5%"
      width="3%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="45%"
      y="30%"
      width="5%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="40%"
      y="32.5%"
      width="10%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="35%"
      y="35%"
      width="15%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="29%"
      y="37.5%"
      width="21%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="27%"
      y="40%"
      width="23%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="26%"
      y="42.5%"
      width="24%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="23%"
      y="45%"
      width="27%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="22%"
      y="47.5%"
      width="28%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="21%"
      y="50%"
      width="29%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="20%"
      y="52.5%"
      width="30%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="19%"
      y="55%"
      width="31%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="18%"
      y="57.5%"
      width="32%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="17%"
      y="60%"
      width="33%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="16%"
      y="62.5%"
      width="34%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="15%"
      y="65%"
      width="35%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="14%"
      y="67.5%"
      width="36%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="13%"
      y="70%"
      width="37%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="12%"
      y="72.5%"
      width="38%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="11%"
      y="75%"
      width="39%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="10%"
      y="77.5%"
      width="40%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="9%"
      y="80%"
      width="41%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="8%"
      y="82.5%"
      width="42%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="7%"
      y="85%"
      width="43%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="6%"
      y="87.5%"
      width="44%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="5%"
      y="90%"
      width="45%"
      height="3%"
      fill="#0082CC"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="22.5%"
      width="1%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="25%"
      width="2%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="27.5%"
      width="3%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="30%"
      width="5%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="32.5%"
      width="10%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="35%"
      width="15%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="37.5%"
      width="21%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="40%"
      width="23%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="42.5%"
      width="24%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="45%"
      width="27%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="47.5%"
      width="28%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="50%"
      width="29%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="52.5%"
      width="30%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="55%"
      width="31%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="57.5%"
      width="32%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="60%"
      width="33%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="62.5%"
      width="34%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="65%"
      width="35%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="67.5%"
      width="36%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="70%"
      width="37%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="72.5%"
      width="38%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="75%"
      width="39%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="77.5%"
      width="40%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="80%"
      width="41%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="82.5%"
      width="42%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="85%"
      width="43%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="87.5%"
      width="44%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    <rect
      x="50%"
      y="90%"
      width="45%"
      height="3%"
      fill="#FB4540"
      rx="5"
      ry="5"
      stroke="#000"
    />
    {/* Text labels for y-axis */}
    {/* ... (text labels for y-axis) */}
    <text x="1%" y="6%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      200%
    </text>
    <text x="1%" y="20%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      100%
    </text>
    <text x="1%" y="34%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      50%
    </text>
    <text x="1%" y="48%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      0%
    </text>
    <text x="1%" y="62%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      -50%
    </text>
    <text x="1%" y="76%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      -100%
    </text>
    <text x="1%" y="90%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      -200%
    </text>

    {/* Text labels for x-axis (month names) */}
    {/* ... (text labels for x-axis) */}
    <text x="10%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Jan
    </text>
    <text x="18%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Feb
    </text>
    <text x="26%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Mar
    </text>
    <text x="34%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Apr
    </text>
    <text x="42%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      May
    </text>
    <text x="50%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Jun
    </text>
    <text x="58%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Jul
    </text>
    <text x="66%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Aug
    </text>
    <text x="74%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Sep
    </text>
    <text x="82%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Oct
    </text>
    <text x="90%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Nov
    </text>
    <text x="98%" y="100%" fontFamily="Arial" fontSize="10" fill="#AEBBDA">
      Dec
    </text>
  </svg>
);

export default Svg;
